### ISSUE TITLE
release

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [appc/acserver#5]
trying to build with
https://github.com/dgonyeo/containers/blob/master/acserver/build-acserver.sh

produces an error

```
github.com/appc/acserver/main.go:163: r.BasicAuth undefined (type *http.Request has no field or method BasicAuth)
```

can you please publish a release?

**Comment by cgonyeo** [comment]
Once https://github.com/appc/acserver/pull/10 is merged I'll tag the commit and upload release artifacts.

**Comment by cgonyeo** [comment]
Just finished making the release: https://github.com/appc/acserver/releases/tag/v0.1.0

**Comment by Andrei-Pozolotin** [comment]
works, thank you
https://aur.archlinux.org/packages/acserver/
